import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F7FB",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  centerHeader: {
    alignItems: "center",
    justifyContent: "center",
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  greeting: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "700",
    textAlign: "center",
  },
  subGreeting: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 13,
    textAlign: "center",
    marginTop: 4,
  },
  card: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 20,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
    gap: 8,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1B2A41",
  },
  deviceRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  deviceBadge: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: "#E3F2FD",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  deviceName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1B2A41",
  },
  deviceStatus: {
    marginTop: 4,
    color: "#2E7D32",
    fontWeight: "600",
  },
  primaryBtn: {
    backgroundColor: "#1565C0",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  primaryBtnNKT: {
    backgroundColor: "#FF3B30",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  primaryBtnText: {
    color: "#fff",
    fontWeight: "700",
  },
  heartCard: {
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 24,
    padding: 18,
  },
  heartTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  heartLabel: {
    color: "#fff",
    fontSize: 14,
    opacity: 0.95,
  },
  heartValue: {
    color: "#fff",
    fontSize: 34,
    fontWeight: "800",
    marginTop: 6,
  },
  heartIconWrap: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  heartDesc: {
    color: "#fff",
    fontSize: 14,
    marginTop: 14,
    lineHeight: 20,
  },
  secondaryWhiteBtn: {
    marginTop: 14,
    backgroundColor: "#fff",
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
  },
  secondaryWhiteBtnText: {
    color: "#E53935",
    fontWeight: "700",
    fontSize: 15,
  },
  alertCard: {
    backgroundColor: "#FFF3F3",
    borderWidth: 1,
    borderColor: "#FFCDD2",
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 18,
    padding: 14,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  alertLeft: {
    marginRight: 10,
    marginTop: 2,
  },
  alertTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#C62828",
    marginBottom: 6,
  },
  alertText: {
    color: "#6D4C41",
    lineHeight: 20,
  },
  sectionHeader: {
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1B2A41",
  },
  quickGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 16,
    gap: 10,
  },
  quickCard: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 14,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  quickIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  quickTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1B2A41",
    textAlign: "center",
  },
  quickDesc: {
    fontSize: 12,
    color: "#607D8B",
    textAlign: "center",
    marginTop: 6,
    lineHeight: 17,
  },
  mapPlaceholder: {
    height: 190,
    borderRadius: 18,
    backgroundColor: "#EEF4F8",
    alignItems: "center",
    justifyContent: "center",
  },
  mapText: {
    marginTop: 10,
    fontSize: 18,
    fontWeight: "700",
    color: "#1B2A41",
  },
  mapSubText: {
    marginTop: 6,
    fontSize: 13,
    color: "#607D8B",
  },
  mapActionBtn: {
    marginTop: 14,
    backgroundColor: "#2E7D32",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
  },
  mapActionBtnText: {
    color: "#fff",
    fontWeight: "700",
  },
  buocChanBtnText: {
    color: "#2E7D32",
    fontWeight: "700",
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  summaryBox: {
    flex: 1,
    backgroundColor: "#F7FAFD",
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: "center",
  },
  summaryNumber: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1565C0",
  },
  summaryLabel: {
    marginTop: 6,
    fontSize: 13,
    color: "#607D8B",
  },
  mainHeartCard: {
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 24,
    padding: 20,
    alignItems: "center",
  },
  mainHeartLabel: {
    color: "#fff",
    fontSize: 15,
    opacity: 0.95,
  },
  mainHeartRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    marginTop: 14,
  },
  mainHeartValue: {
    color: "#fff",
    fontSize: 48,
    fontWeight: "800",
    marginLeft: 12,
  },
  mainHeartUnit: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 8,
    marginBottom: 8,
  },
  mainHeartWarning: {
    color: "#fff",
    marginTop: 14,
    fontSize: 15,
    fontWeight: "600",
  },
  fakeChart: {
    height: 180,
    borderRadius: 18,
    backgroundColor: "#F8FBFF",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  chartPeakWrap: {
    height: 80,
    justifyContent: "space-between",
    marginBottom: 24,
  },
  chartLineLow: {
    width: "35%",
    height: 4,
    borderRadius: 4,
    backgroundColor: "#90CAF9",
  },
  chartLinePeak: {
    width: "90%",
    height: 4,
    borderRadius: 4,
    backgroundColor: "#E53935",
  },
  chartLineMid: {
    width: "55%",
    height: 4,
    borderRadius: 4,
    backgroundColor: "#42A5F5",
  },
  chartTime: {
    color: "#78909C",
    fontSize: 12,
    textAlign: "center",
  },
  historyItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#ECEFF1",
  },
  historyTime: {
    fontSize: 14,
    color: "#607D8B",
    fontWeight: "600",
  },
  historyValue: {
    fontSize: 14,
    color: "#1B2A41",
    fontWeight: "600",
  },
  historyValueHigh: {
    fontSize: 14,
    color: "#D32F2F",
    fontWeight: "700",
  },
  locationMap: {
    height: 260,
    borderRadius: 20,
    backgroundColor: "#E8F5E9",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  locationPin: {
    position: "absolute",
    top: 55,
    right: 70,
  },
  locationMapTitle: {
    marginTop: 14,
    fontSize: 18,
    fontWeight: "700",
    color: "#1B2A41",
  },
  locationMapSub: {
    marginTop: 6,
    fontSize: 14,
    color: "#607D8B",
  },
  infoItem: {
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: "#ECEFF1",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  infoItemNoBorder: {
    paddingVertical: 13,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  infoLabel: {
    fontSize: 14,
    color: "#607D8B",
    flex: 1,
  },
  infoValue: {
    fontSize: 14,
    color: "#1B2A41",
    fontWeight: "700",
    flex: 1,
    textAlign: "right",
  },
  safeZoneText: {
    fontSize: 14,
    lineHeight: 22,
    color: "#455A64",
  },
  profileCard: {
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 22,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  avatarWrap: {
    width: 84,
    height: 84,
    borderRadius: 42,
    backgroundColor: "#F3E5F5",
    alignItems: "center",
    justifyContent: "center",
  },
  profileName: {
    marginTop: 14,
    fontSize: 22,
    fontWeight: "800",
    color: "#1B2A41",
  },
  profileRole: {
    marginTop: 6,
    fontSize: 14,
    color: "#7B8794",
  },
  profileTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    marginTop: 14,
  },
  profileTag: {
    backgroundColor: "#F3E5F5",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  profileTagText: {
    color: "#6A1B9A",
    fontWeight: "700",
    fontSize: 12,
  },
  switchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
  },
  switchLabel: {
    fontSize: 15,
    color: "#1B2A41",
    fontWeight: "600",
    flex: 1,
    paddingRight: 12,
  },
  profileSummaryText: {
    fontSize: 14,
    lineHeight: 22,
    color: "#455A64",
  },
});
