import { ENV } from "../../constants/env";
import { ApiConfig } from "../core/types";

export const monitorApiS: Record<string, ApiConfig> = {
    getMonitorByUser: {
        name: "getMonitorByUser",
        baseUrl: ENV.USER_API_BASE_URL,
        endpoint: "/api/monitor/getListMonitor",
        method: "GET",
        timeout: ENV.DEFAULT_TIMEOUT,
        retries: 2,
        authType: "bearer",
        headers: {
            "Content-Type": "application/json",
        },
        token: "USER_ACCESS_TOKEN",
        transformResponse: (data) => data?.data || data,
    },

    getMonitorIdDetailSoure: {
        name: "getMonitorIdDetailSoure",
        baseUrl: ENV.USER_API_BASE_URL,
        endpoint: "/api/monitor/getMonitorIdDetail",
        method: "GET",
        timeout: ENV.DEFAULT_TIMEOUT,
        retries: 2,
        authType: "bearer",
        headers: {
            "Content-Type": "application/json",
        },
        token: "USER_ACCESS_TOKEN",
        transformResponse: (data) => data?.data || data,
    },
    getPendingRequests: {
        name: "getPendingRequests",
        baseUrl: ENV.USER_API_BASE_URL,
        endpoint: "/api/monitor/pending-requests",
        method: "GET",
        timeout: ENV.DEFAULT_TIMEOUT,
        retries: 2,
        authType: "bearer",
        headers: {
            "Content-Type": "application/json",
        },
        token: "USER_ACCESS_TOKEN",
        transformResponse: (data) => data?.data || data,
    },
    getFollowing: {
        name: "getFollowing",
        baseUrl: ENV.USER_API_BASE_URL,
        endpoint: "/api/monitor/following",
        method: "GET",
        timeout: ENV.DEFAULT_TIMEOUT,
        retries: 2,
        authType: "bearer",
        headers: {
            "Content-Type": "application/json",
        },
        token: "USER_ACCESS_TOKEN",
        transformResponse: (data) => data?.data || data,
    },
    sendFollowRequestByPhone: {
        name: "sendFollowRequestByPhone",
        baseUrl: ENV.USER_API_BASE_URL,
        endpoint: "/api/monitor/request-by-phone",
        method: "POST",
        timeout: ENV.DEFAULT_TIMEOUT,
        retries: 2,
        authType: "bearer",
        headers: {
            "Content-Type": "application/json",
        },
        token: "USER_ACCESS_TOKEN",
        transformResponse: (data) => data?.data || data,
    },
    getFollowers: {
        name: "getFollowers",
        baseUrl: ENV.USER_API_BASE_URL,
        endpoint: "/api/monitor/followers",
        method: "GET",
        timeout: ENV.DEFAULT_TIMEOUT,
        retries: 2,
        authType: "bearer",
        headers: {
            "Content-Type": "application/json",
        },
        token: "USER_ACCESS_TOKEN",
        transformResponse: (data) => data?.data || data,
    },
    approveRequest: {
        name: "approveRequest",
        baseUrl: ENV.USER_API_BASE_URL,
        endpoint: "/api/monitor/approve-request",
        method: "POST",
        timeout: ENV.DEFAULT_TIMEOUT,
        retries: 2,
        authType: "bearer",
        headers: {
            "Content-Type": "application/json",
        },
        token: "USER_ACCESS_TOKEN",
        transformResponse: (data) => data?.data || data,
    },
    cancelMonitoring: {
        name: "cancelMonitoring",
        baseUrl: ENV.USER_API_BASE_URL,
        endpoint: "/api/monitor/cancel-monitoring",
        method: "POST",
        timeout: ENV.DEFAULT_TIMEOUT,
        retries: 2,
        authType: "bearer",
        headers: {
            "Content-Type": "application/json",
        },
        token: "USER_ACCESS_TOKEN",
        transformResponse: (data) => data?.data || data,
    },

    cancelFollower: {
        name: "cancelFollower",
        baseUrl: ENV.USER_API_BASE_URL,
        endpoint: "/api/monitor/cancel-follower",
        method: "POST",
        timeout: ENV.DEFAULT_TIMEOUT,
        retries: 2,
        authType: "bearer",
        headers: {
            "Content-Type": "application/json",
        },
        token: "USER_ACCESS_TOKEN",
        transformResponse: (data) => data?.data || data,
    },
};
